/**
 * .env file parser and credential grouping for `aura env init`
 */

import { isValidEnvVarName } from './credential-resolve';

export interface CredentialGroup {
  name: string;
  fields: Array<{ key: string; value: string; envVar: string }>;
}

/**
 * Parse a .env file into key-value pairs.
 * Handles: comments, blank lines, `export` prefix, single/double quotes, escaped chars.
 * Does NOT handle: multiline values, variable expansion.
 */
export function parseDotenv(content: string): Map<string, string> {
  const result = new Map<string, string>();

  for (const rawLine of content.split('\n')) {
    const line = rawLine.trim();

    // Skip empty lines and comments
    if (!line || line.startsWith('#')) continue;

    // Strip optional `export ` prefix
    const stripped = line.startsWith('export ') ? line.slice(7).trim() : line;

    const eqIdx = stripped.indexOf('=');
    if (eqIdx === -1) continue;

    const key = stripped.substring(0, eqIdx).trim();
    if (!key) continue;

    // Validate env var name (audit finding #6)
    if (!isValidEnvVarName(key)) {
      console.error(`warning: skipping invalid env var name '${key}'`);
      continue;
    }

    let value = stripped.substring(eqIdx + 1).trim();

    // Handle quoted values
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      const quote = value[0];
      value = value.slice(1, -1);
      if (quote === '"') {
        // Unescape double-quoted values
        value = value
          .replace(/\\n/g, '\n')
          .replace(/\\r/g, '\r')
          .replace(/\\t/g, '\t')
          .replace(/\\"/g, '"')
          .replace(/\\\\/g, '\\');
      }
      // Single-quoted: literal, no escaping
    } else {
      // Unquoted: strip inline comment
      const commentIdx = value.indexOf(' #');
      if (commentIdx !== -1) {
        value = value.substring(0, commentIdx).trim();
      }
    }

    result.set(key, value);
  }

  return result;
}

/**
 * Group env vars by common prefix for credential creation.
 *
 * Rules:
 * - Split var name by `_`, use first segment as group prefix
 * - Groups with 1 member: credential name = full lowercased var name, field = "value"
 * - Groups with 2+ members: credential name = prefix, field = rest lowercased
 */
export function groupByPrefix(vars: Map<string, string>): CredentialGroup[] {
  const prefixGroups = new Map<string, Array<{ key: string; value: string; envVar: string }>>();

  for (const [envVar, value] of vars) {
    const underscoreIdx = envVar.indexOf('_');
    const prefix = underscoreIdx === -1
      ? envVar.toLowerCase()
      : envVar.substring(0, underscoreIdx).toLowerCase();

    if (!prefixGroups.has(prefix)) {
      prefixGroups.set(prefix, []);
    }

    const fieldName = underscoreIdx === -1
      ? 'value'
      : envVar.substring(underscoreIdx + 1).toLowerCase();

    prefixGroups.get(prefix)!.push({ key: fieldName, value, envVar });
  }

  const groups: CredentialGroup[] = [];

  for (const [prefix, fields] of prefixGroups) {
    if (fields.length === 1 && fields[0].key !== 'value') {
      groups.push({
        name: fields[0].envVar.toLowerCase(),
        fields: [{ key: 'value', value: fields[0].value, envVar: fields[0].envVar }],
      });
    } else {
      groups.push({ name: prefix, fields });
    }
  }

  return groups;
}

/**
 * No grouping — one credential per env var, field always "value".
 */
export function noGrouping(vars: Map<string, string>): CredentialGroup[] {
  const groups: CredentialGroup[] = [];
  for (const [envVar, value] of vars) {
    groups.push({
      name: envVar.toLowerCase(),
      fields: [{ key: 'value', value, envVar }],
    });
  }
  return groups;
}

/**
 * Generate .aura file content from credential groups.
 */
export function generateAuraFile(groups: CredentialGroup[]): string {
  const lines = ['# Generated by aura env init'];

  for (const group of groups) {
    for (const field of group.fields) {
      const ref = field.key === 'value'
        ? `${group.name}/value`
        : `${group.name}/${field.key}`;
      lines.push(`${field.envVar}=${ref}`);
    }
  }

  return lines.join('\n') + '\n';
}
